### ISSUE TITLE
Relationships

### ISSUE THREAD

**Issue by ghost** [dannyweeks/laravel-base-repository#1]
I really like the start of your BaseRepository however something to think about is the relationships. What if in the situation you do have more than one relationship BUT you don't want to load all relationships ALL the time. You need to thin of a way to only need to load one relationship or two instead of every relationship.

**Comment by dannyweeks** [comment]
That's a fair point mate. Do you think it's acceptable to pull in all by default and maybe have a method to override the relationships that are pulled in a method chain? I do have some other additions to make to the repository, being the rest of CRUD since in its present form it actually only does the R!

**Comment by ghost** [comment]
Honestly I don't believe it is best to pull in by default. I think you should make it NULL or an empty array and have the developer insert which ones they want. I feel its easier to do it this way then to tell it which relationships you don't want to include.

When shall we expect an update?

**Comment by dannyweeks** [comment]
I will work on it over the next could of days.

**Comment by ghost** [comment]
Any update?

**Comment by dannyweeks** [comment]
@jeffreydavidsonfullsail sorry it took much longer. I was hung up over complicating it and have been busy in work. Tell me what you think!
