### ISSUE TITLE
Trait ThrowsHttpExceptions not found

### ISSUE THREAD

**Issue by kingsloi** [dannyweeks/laravel-base-repository#2]
Hey, great base repo!

I've followed your instructions and tried to implement the ThrowHttpExceptions trait but it look like it isn't in the package?

**Comment by dannyweeks** [comment]
Hey @kingsloi,

Thanks, I'm glad you like it! 

I haven't tagged it yet since making a lot of additions including the one you have mentioned. This means that the latest changes aren't available unless you specify the to use the master branch. You can do this two ways:

`composer require dannyweeks/laravel-base-repository:dev-master`

or update your `composer.json` file with:

```
"dannyweeks/laravel-base-repository": "dev-master"
```

I do plan on releasing a stable version soon, just have a few more little features to add!

Any problems just give me a shout!

Danny

**Comment by kingsloi** [comment]
Hey @dannyweeks, cheers for the update! 

not to worry - I'll wait until it's stable and then update. Thanks for letting me know!

**Comment by dannyweeks** [comment]
FYI @kingsloi I just tagged version 1!

https://github.com/dannyweeks/laravel-base-repository/releases/tag/v1.0
